sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: ./gradlew --version

script:
  - ./gradlew -DbuildVersion=travis-${TRAVIS_BUILD_NUMBER} clean build
  - ./gradlew asciidoctor scaladoc
  - ./gradlew skysail.server.app.bookmarks:export.server.app.bookmarks.docker
  - ./gradlew copyConf copyRunnables

after_success:
  - docker --version
  - docker build -t evandor/skysail-server-app-bookmarks:${TRAVIS_BUILD_NUMBER} skysail.server.app.bookmarks/release
  - docker images
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/skysail-server-app-bookmarks:${TRAVIS_BUILD_NUMBER}

notifications:
    slack: skysail-io:QGRw4Q2CzA56P0c9p5M5xwlm
    webhooks:
      urls:
        - http://jenkins.twentyeleven.de/generic-webhook-trigger/invoke
      on_success: always # default: always
      on_failure: never # default: always
      on_cancel: never # default: always
      on_error: never # default: always